# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    ruby: "3.3"
  jobs:
    pre_build:
      - gem install html-proofer -v ">= 5.0.9"  # Ensure version >= 5.0.9
      - htmlproofer --version  # Verify the version of html-proofer installed
      - htmlproofer --help
    post_build:
      # Check everything but the reference (because mkdocstrings do not set href=)
      - htmlproofer $READTHEDOCS_OUTPUT/html  --checks Links,Scripts \
        --ignore-urls "https://fonts.gstatic.com,https://doi.org/10.1523/JNEUROSCI.3305-05.2005" \
        --assume-extension --check-external-hash \
        --ignore-status-codes 403 \
        --ignore-files "/.+\/site\/reference\/.+/"
      # Check the reference allowing missing href
      - htmlproofer $READTHEDOCS_OUTPUT/html \
        --assume-extension --check-external-hash \
        --ignore-urls "https://fonts.gstatic.com" \
        --allow-missing-href --ignore-status-codes 403

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs

formats:
  - pdf
  - htmlzip
