# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    ruby: "3.3"
  jobs:
    pre_build:
      - gem install html-proofer -v ">= 5.0.9"  # Ensure version >= 5.0.9
      - python -c "import os; print('READTHEDOCS_OUTPUT:', os.environ.get('READTHEDOCS_OUTPUT'))"
    post_build:
      - python -c "import os; print('READTHEDOCS_OUTPUT:', os.environ.get('READTHEDOCS_OUTPUT'))"
      - python post_build.py
      # Check everything except 403s and a jneurosci, which returns 404 but the link works when clicking.
      - htmlproofer $READTHEDOCS_OUTPUT/html  --checks Links,Scripts,Images --ignore-urls "https://fonts.gstatic.com,https://www.jneurosci.org/content/25/47/11003" --assume-extension --check-external-hash --ignore-status-codes 403 --ignore-files "/.+\/_static\/.+/","/.+\/stubs\/.+/","/.+\/tutorials/plot_02_head_direction.+/"
      # The auto-generated animation doesn't have a alt or src/srcset; I am able to ignore missing alt, but I cannot work around a missing src/srcset
      # therefore for this file I am not checking the figures.
      - htmlproofer $READTHEDOCS_OUTPUT/html/tutorials/plot_02_head_direction.html  --checks Links,Scripts --ignore-urls "https://www.jneurosci.org/content/25/47/11003"
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs

formats:
  - pdf
  - htmlzip
