# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    ruby: "3.3"
  jobs:
    pre_build:
      - gem install html-proofer -v ">= 5.0.9"  # Ensure version >= 5.0.9
    post_build:
      # Check everything but the reference (because mkdocstrings do not set href=)
      - htmlproofer $READTHEDOCS_OUTPUT/html  --checks Links,Scripts --ignore-urls "https://fonts.gstatic.com,https://www.jneurosci.org/content/25/47/11003" --assume-extension --check-external-hash --ignore-status-codes 403 --ignore-files "/.+\/_static\/.+/","/.+\/stubs\/.+/"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs

formats:
  - pdf
  - htmlzip
