site_name: NeMoS
repo_url: https://github.com/flatironinstitute/nemos

theme:
  name: 'material'                         # The theme name, using the 'material' theme
  favicon: assets/NeMoS_favicon.ico
  logo: assets/NeMoS_Icon_CMYK_White.svg
  palette:
    primary: 'light blue'                   # The primary color palette for the theme
    features:
      - navigation.tabs                    # Enable navigation tabs feature for the theme
  markdown_extensions:
    - attr_list
    - admonition
    - tables
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - search.highlights
    - search.share
    - search.suggest

markdown_extensions:
    - md_in_html
    - footnotes
    - pymdownx.superfences
    - pymdownx.details # add notes toggleable notes ???


plugins:
  - search
  - gallery:
        conf_script: docs/gallery_conf.py
        # path to the directory containing our background/tutorials
        examples_dirs:
          - docs/background
          - docs/how_to_guide
          - docs/tutorials
        # path to the directory where mkdocs will save the generated output
        gallery_dirs:
          - docs/generated/background
          - docs/generated/how_to_guide
          - docs/generated/tutorials
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py            # Specify the script to generate the code reference pages
  - literate-nav:
        nav_file: docs/SUMMARY.md           # Specify the navigation file for literate-style navigation
  - section-index                           # Enable the section-index plugin for generating a section index
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            members_order: source
            inherited_members: true

extra_javascript:
  - javascripts/katex.js
  - javascripts/toggle_code.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - assets/stylesheets/extra.css

nav:
    - Home: index.md                          # Link to the index.md file (home page)
    - Install: installation.md # Link to the installation.md file
    - Quickstart: quickstart.md
    - Background: generated/background    # Link to the generated gallery Tutorials
    - How-To-Guide: generated/how_to_guide # Link to the generated gallery tutorials
    - Tutorials: generated/tutorials # Link to the generated gallery tutorials
    - API Guide: reference/             # Link to the reference/ directory
    - For Developers: developers_notes/       # Link to the developers notes
